<?php

namespace AppBundle\Repository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAVenir(){

  		$gestionnaireEntity= $this->_em;
  		$requete=$gestionnaireEntity->createQuery("SELECT i FROM AppBundle:Episode i 
											 	   WHERE i.date > CURRENT_DATE() 
											       ORDER BY i.date ASC");									
   		$tabEpisode = $requete->getResult();
   		return $tabEpisode;
	}
}
